const fileMap = {
    "Fleshlight":                                       "xml/base/fleshlight.xml",
    "Férfi örömszerző":                                 "",
    "......Művagina, maszturbátor":                     "xml/base/base.xml",
    "......Péniszgyűrű":                                "xml/base/base.xml",
    "......Péniszköpeny / péniszhosszabbító":           "xml/base/base.xml",
    "......Péniszmandzsetta":                           "xml/base/base.xml",
    "......Péniszpumpa":                                "xml/base/base.xml",
    "......Prosztata masszírozó":                       "xml/base/base.xml",
    "......Szexbaba":                                   "xml/base/base.xml",
    "Kényeztetés Hölgyeknek":                           "",
    "......Csiklóizgató":                               "xml/base/base.xml",
    "............Léghullámos csiklóizgató":             "xml/base/base.xml",
    "......Gésagolyó":                                  "xml/base/base.xml",
    "......Szemérem- és mellpumpa":                     "xml/base/base.xml",
    "......Vibrációs tojás":                            "xml/base/base.xml",
    "Anál szex":                                        "",
    "......Anál drogéria":                              "xml/base/base.xml",
    "......Anális izgató / plug":                       "xml/base/base.xml",
    "Potencianövelő":                                   "",
    "......Alkalmi potencianövelő":                     "xml/base/base.xml",
    "......Kúraszerű potencianövelő":                   "xml/base/base.xml",
    "BDSM":                                             "",
    "......BDSM készlet":                               "xml/base/base.xml",
    "......Nyakörv és póráz":                           "xml/base/base.xml",
    "......Bilincs és kötöző":                          "xml/base/base.xml",
    "......Korbács, paskoló és cirógató":               "xml/base/base.xml",
    "......Maszk és szemkötő":                          "xml/base/base.xml",
    "......Mellcsipesz":                                "xml/base/base.xml",
    "......S/M kiegészítő":                             "xml/base/base.xml",
    "......Szájpecek":                                  "xml/base/base.xml",
    "......Szexhinta":                                  "xml/base/base.xml",
    "Dildó (műpénisz)":                                 "",
    "......Anál dildó":                                 "xml/base/base.xml",
    "......Élethű dildó":                               "xml/base/base.xml",
    "......Felcsatolható műpénisz":                     "xml/base/base.xml",
    "......Felpumpálható és spriccelő műpénisz":        "xml/base/base.xml",
    "......G-pont izgató":                              "xml/base/base.xml",
    "......Kétvégű, páros dildó":                       "xml/base/base.xml",
    "......Színes és üveg dildó":                       "xml/base/base.xml",
    "......Tapadókorongos dildó":                       "xml/base/base.xml",
    "Vibrátorok":                                       "",
    "......Anál vibrátor":                              "xml/base/base.xml",
    "......Csikló vibrátor (klitoriszkaros)":           "xml/base/base.xml",
    "......Felcsatolható vibrátor":                     "xml/base/base.xml",
    "......Gpont vibrátor":                             "xml/base/base.xml",
    "......Gyöngyös vibrátor":                          "xml/base/base.xml",
    "......Klasszikus (rúdvibrátor)":                   "xml/base/base.xml",
    "......Letapasztható vibrátor":                     "xml/base/base.xml",
    "......Masszírozó (wand)":                          "xml/base/base.xml",
    "......Okos vibrátor (mobil applikációval)":        "xml/base/base.xml",
    "......Párvibrátor":                                "xml/base/base.xml",
    "......Realisztikus vibrátor":                      "xml/base/base.xml",
    "Szexpatika":                                       "",
    "......Síkosítók":                                  "xml/base/base.xml",
    "............Anál síkosító":                        "xml/base/base.xml",
    "............Hűsítő vagy melegítő síkosító":        "xml/base/base.xml",
    "............Illatosított és ízesített síkosító":   "xml/base/base.xml",
    "............Vegán és BIO síkosító":                "xml/base/base.xml",
    "............Szilikonos síkosító":                  "xml/base/base.xml",
    "............Vízbázisú síkosító":                   "xml/base/base.xml",
    "......Masszázsolaj és masszázskrém":               "xml/base/base.xml",
    "......Óvszer":                                     "xml/base/base.xml",
    "......Intim higiénia":                             "xml/base/base.xml",
    "......Késleltető":                                 "xml/base/base.xml",
    "......Pénisznövelő":                               "xml/base/base.xml",
    "......Testfesték":                                 "xml/base/base.xml",
    "......Vágyfokozó":                                 "xml/base/base.xml",
    "......Feromonos parfüm":                           "xml/base/base.xml",
    "......Bőrtisztító folyadék":                       "xml/base/base.xml",
    "Fehérneműk":                                       "",
    "......Babydoll és neglizsé":                       "xml/base/base.xml",
    "......Bodyk":                                      "xml/base/base.xml",
    "......Cicaruha":                                   "xml/base/base.xml",
    "......Erotikus kiegészítő":                        "xml/base/base.xml",
    "......Férfi fehérnemű":                            "xml/base/base.xml",
    "......Fűző és míder":                              "xml/base/base.xml",
    "......Harisnya":                                   "xml/base/base.xml",
    "......Latex és bőrhatású ruha":                    "xml/base/base.xml",
    "......Miniruha és szoknya":                        "xml/base/base.xml",
    "......Szexi fehérnemű, bikini és szettek":         "xml/base/base.xml",
    "......Szexi jelmezek":                             "xml/base/base.xml",
    "Erotikus játék és ajándék":                        "",
    "......Felnőtt társasjáték":                        "xml/base/base.xml",
    "......Lánybúcsúra":                                "xml/base/base.xml",
    "......Legénybúcsúra":                              "xml/base/base.xml",
    "......Party kellék, vicces tárgyak és ajándékok":  "xml/base/base.xml",
    "Segédeszköz kiegészítő":                           "",
    "......Eszköztisztító és -ápoló":                   "xml/base/base.xml",
    "......Tartozékok játékszerekhez":                  "xml/base/base.xml"
};

const fileMap_inLinks = {
    "Fleshlight":                                       "",
    "Férfi örömszerző":                                 "",
    "......Művagina, maszturbátor":                     "xml/inlinks/ferfiaknak/muvagina.xml",
    "......Péniszgyűrű":                                "xml/inlinks/ferfiaknak/peniszgyuru.xml",
    "......Péniszköpeny / péniszhosszabbító":           "xml/inlinks/ferfiaknak/peniszkopeny.xml",
    "......Péniszmandzsetta":                           "xml/inlinks/ferfiaknak/peniszmandzsetta.xml",
    "......Péniszpumpa":                                "xml/inlinks/ferfiaknak/peniszpumpa.xml",
    "......Prosztata masszírozó":                       "xml/inlinks/ferfiaknak/prosztata.xml",
    "......Szexbaba":                                   "xml/inlinks/ferfiaknak/szexbaba.xml",
    "Kényeztetés Hölgyeknek":                           "",
    "......Csiklóizgató":                               "xml/inlinks/noknek/csikloizgato.xml",
    "............Léghullámos csiklóizgató":             "xml/inlinks/noknek/leghullamos-csikloizgato.xml",
    "......Gésagolyó":                                  "xml/inlinks/noknek/gesagolyo.xml",
    "......Szemérem- és mellpumpa":                     "",
    "......Vibrációs tojás":                            "xml/inlinks/noknek/tojasvibrator.xml",
    "Anál szex":                                        "",
    "......Anál drogéria":                              "",
    "......Anális izgató / plug":                       "",
    "Potencianövelő":                                   "",
    "......Alkalmi potencianövelő":                     "xml/inlinks/potencianovelo/alkalmi-potencianovelo.xml",
    "......Kúraszerű potencianövelő":                   "xml/inlinks/potencianovelo/kuraszeru-potencianovelo.xml",
    "BDSM":                                             "",
    "......BDSM készlet":                               "xml/inlinks/bdsm/bdsm.xml",
    "......Nyakörv és póráz":                           "xml/inlinks/bdsm/bdsm.xml",
    "......Bilincs és kötöző":                          "xml/inlinks/bdsm/bdsm.xml",
    "......Korbács, paskoló és cirógató":               "xml/inlinks/bdsm/bdsm.xml",
    "......Maszk és szemkötő":                          "xml/inlinks/bdsm/bdsm.xml",
    "......Mellcsipesz":                                "xml/inlinks/bdsm/bdsm.xml",
    "......S/M kiegészítő":                             "xml/inlinks/bdsm/bdsm.xml",
    "......Szájpecek":                                  "xml/inlinks/bdsm/bdsm.xml",
    "......Szexhinta":                                  "xml/inlinks/bdsm/bdsm.xml",
    "Dildó (műpénisz)":                                 "",
    "......Anál dildó":                                 "xml/inlinks/dildo/anal-dilo.xml",
    "......Élethű dildó":                               "xml/inlinks/dildo/elethu-dildo.xml",
    "......Felcsatolható műpénisz":                     "xml/inlinks/dildo/felcsatolhato-dildo.xml",
    "......Felpumpálható és spriccelő műpénisz":        "xml/inlinks/dildo/spriccelo-dildo.xml",
    "......G-pont izgató":                              "",
    "......Kétvégű, páros dildó":                       "xml/inlinks/dildo/ketvegu-paros-dildo.xml",
    "......Színes és üveg dildó":                       "xml/inlinks/dildo/szines-es-uveg-dildo.xml",
    "......Tapadókorongos dildó":                       "xml/inlinks/dildo/letapaszthato-dildo.xml",
    "Vibrátorok":                                       "",
    "......Anál vibrátor":                              "xml/inlinks/vibrator/anal-vibrator.xml",
    "......Csikló vibrátor (klitoriszkaros)":           "xml/inlinks/vibrator/csikloizgatos-vibrator.xml",
    "......Felcsatolható vibrátor":                     "xml/inlinks/vibrator/felcsatolhato-vibrator.xml",
    "......Gpont vibrátor":                             "xml/inlinks/vibrator/g-pont-vibrator.xml",
    "......Gyöngyös vibrátor":                          "xml/inlinks/vibrator/gyongyos-vibrator.xml",
    "......Klasszikus (rúdvibrátor)":                   "xml/inlinks/vibrator/klasszikus-rudvibrator.xml",
    "......Letapasztható vibrátor":                     "xml/inlinks/vibrator/letapaszthato-vibrator.xml",
    "......Masszírozó (wand)":                          "xml/inlinks/vibrator/masszirozo-wand.xml",
    "......Okos vibrátor (mobil applikációval)":        "xml/inlinks/vibrator/okos-vibrator.xml",
    "......Párvibrátor":                                "xml/inlinks/vibrator/parvibrator.xml",
    "......Realisztikus vibrátor":                      "xml/inlinks/vibrator/elethu-vibrator.xml",
    "Szexpatika":                                       "",
    "......Síkosítók":                                  "",
    "............Anál síkosító":                        "xml/inlinks/sikosito/anal-sikosito.xml",
    "............Hűsítő vagy melegítő síkosító":        "xml/inlinks/sikosito/husito-melegito-sikosíto.xml",
    "............Illatosított és ízesített síkosító":   "xml/inlinks/sikosito/izesitett-illatos-sikosito.xml",
    "............Vegán és BIO síkosító":                "xml/inlinks/sikosito/vegan-bio-sikosito.xml",
    "............Szilikonos síkosító":                  "xml/inlinks/sikosito/szilikonos-sikosito.xml",
    "............Vízbázisú síkosító":                   "xml/inlinks/sikosito/vizbazisu-sikosito.xml",
    "......Masszázsolaj és masszázskrém":               "xml/inlinks/masszazsolaj-masszazskrem.xml",
    "......Óvszer":                                     "xml/inlinks/ovszer.xml",
    "......Intim higiénia":                             "",
    "......Késleltető":                                 "xml/inlinks/keslelteto.xml",
    "......Pénisznövelő":                               "xml/inlinks/penisznovelo.xml",
    "......Testfesték":                                 "xml/inlinks/testfestek.xml",
    "......Vágyfokozó":                                 "xml/inlinks/vagyfokozo.xml",
    "......Feromonos parfüm":                           "xml/inlinks/feromonos-parfum.xml",
    "......Bőrtisztító folyadék":                       "",
    "Fehérneműk":                                       "",
    "......Babydoll és neglizsé":                       "",
    "......Bodyk":                                      "",
    "......Cicaruha":                                   "",
    "......Erotikus kiegészítő":                        "",
    "......Férfi fehérnemű":                            "",
    "......Fűző és míder":                              "",
    "......Harisnya":                                   "",
    "......Latex és bőrhatású ruha":                    "",
    "......Miniruha és szoknya":                        "",
    "......Szexi fehérnemű, bikini és szettek":         "",
    "......Szexi jelmezek":                             "",
    "Erotikus játék és ajándék":                        "",
    "......Felnőtt társasjáték":                        "",
    "......Lánybúcsúra":                                "",
    "......Legénybúcsúra":                              "",
    "......Party kellék, vicces tárgyak és ajándékok":  "",
    "Segédeszköz kiegészítő":                           "",
    "......Eszköztisztító és -ápoló":                   "xml/inlinks/eszkoztisztito.xml",
    "......Tartozékok játékszerekhez":                  ""
};